import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { RegisterConstant } from '../RegisterCourse.constant';
import { ProductDTO } from './ProductDTO.model';
import { LoginUserDTO } from './LoginUserDTO.model';
import { RegisterUserDTO } from './RegisterUserDTO.model';
import { AdminUserDTO } from './AdminUserDTO';
import { UserProfile } from './UserProfile.model';
import { FeedbackDTO } from './FeedbackDTO.model';
import { CategoryDTO } from './CategoryDTO.model';
import { AddCart } from './addCart.model';
import { CartDTO } from './cartDTO.model';
import { CreateOrder } from './createOrder.model';
@Injectable({
  providedIn: 'root',
})
export class WebsiteAPIService{
    private httpHeaders: HttpHeaders;
    private urlLoginUser = 'login-user';
    private urlCheckExisted = 'check-existed-and-send-confirm-mail';
    private urlCheckExistedAndSendConfirmChangeMail = 'check-existed-and-send-confirm-change-email?email=';
    private urlRegisterUser = 'register-user';
    private urlGetUsers = 'get-users';
    private urlSendForgetCode = 'send-forget-code?email=';
    private urlChangePassword = 'change-password';
    private urlInActiveUser = 'active-or-inactive-user?loginName=';
    private urlEditUser = 'edit-user';
    private urlUpdateProfile = 'update-profile';
    private urlSetManagerPermisson = 'set-manager-permisson?userId='; 
    private urlCreateProduct = 'create-product'; 
    private urlUpdateProduct = 'update-product';              
    private urlFeedbackCourse = 'feedback-course';
    private urlGetInfoUser = 'get-info-user?userId='; 
    private urlAutoGeneratedProductID = 'auto-generated-product-id';    
    private urlGetAllBrand = 'get-all-brand?type=';
    private urlGetExistedBrand = 'get-existed-brand?brandId=';
    private urlinActiveBrand = 'inactive-brand?brandId=';
    private urlCreateBrand = 'create-brand'; 
    private urlUpdateBrand = 'update-brand';   
    private urlgetAllProduct = 'get-all-product?type=';
    private urlgetExistedProduct = 'get-existed-product?productId=';
    private urlinActiveProduct = 'inactive-product?productId=';
    private urlGetProductsByCategoryID = 'get-products-by-category-id?categoryId=';
    private urlAddCard = 'add-cart';
    private urlGetCartByUserID = 'get-cart-by-user-id?userId=';
    private urlGetWaitingOrderByUserID = 'get-waiting-order-by-user-id?userId=';
    private urlGetProcessingOrderByUserID = 'get-processing-order-by-user-id?userId=';
    private urlGetSuccessOrderByUserID = 'get-success-order-by-user-id?userId=';
    private urlGetCancelOrderByUserID = 'get-cancel-order-by-user-id?userId=';
    private urlDeleteAllCartAfterOrder = 'delete-all-cart-after-order-by-user-id?userId=';
    private urlInActiveCart = 'inactive-cart';
    private urlCreateOrder = 'create-order';
    private urlGetAllProductByOrderID = 'get-all-product-by-oder-id?orderId=';
    private urlCancelOrder = 'cancel-order?orderId=';
    private urlConfirmOrder = 'confirm-order?orderId=';
    private urlSuccessOrder = 'success-order?orderId=';
    private urlGetWaitingOrder = 'get-waiting-order';
    private urlGetProcessingOrder = 'get-processing-order';
    private urlGetSuccessOrder = 'get-success-order';
    private urlGetCancelOrder = 'get-cancel-order';

    //Category service
    private urlgetAllCategory = '?type='; 
    private urlinActiveCategory = 'inactive-category?categoryId=';
    private urlgetExistedCategory = 'get-existed-category?categoryId=';
    private urlCreateCategory = '';
    private urlUpdateCategory = 'update-category';  

    constructor(private http: HttpClient){
        this.httpHeaders = new HttpHeaders({
            "ngrok-skip-browser-warning":"any",
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST, PUT, GET, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With'
        });
    }
    loginUser(user: LoginUserDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlLoginUser, user);
    }
    checkExistedAndSendConfirmMail(user: RegisterUserDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlCheckExisted, user);
    }
    checkExistedAndSendChangeConfirmMail(email: string){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlCheckExistedAndSendConfirmChangeMail + email, {headers: this.httpHeaders});
    }
    registerUser(user: RegisterUserDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlRegisterUser, user);
    }
    getUsers(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetUsers,{ headers: this.httpHeaders});
    }
    sendForgetCode(email: any){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlSendForgetCode + email, {headers: this.httpHeaders});
    }
    changePassword(user: LoginUserDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlChangePassword, user);
    }
    activeOrInActiveUser(loginName : string){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlInActiveUser + loginName, {headers: this.httpHeaders});
    }
    editUser(user: AdminUserDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlEditUser, user);
    }
    updateProfile(user: UserProfile){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlUpdateProfile, user);
    }
    setManagerPermisson(userId : number){ 
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlSetManagerPermisson + userId, {headers: this.httpHeaders});
    }
    createProduct(product: ProductDTO){
        delete product.BrandName;
        return this.http.post<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlCreateProduct, product);
    }
    updateProduct(product: ProductDTO){
        delete product.BrandName;
        return this.http.post<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlUpdateProduct, product);
    }
    inActiveProduct(productId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlinActiveProduct + productId, {headers: this.httpHeaders});
    }
    feedbackCourse(feedback: FeedbackDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlFeedbackCourse, feedback);
    }
    getInfoUser(userId : number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetInfoUser + userId, {headers: this.httpHeaders});
    }
    autoGeneratedProductID(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlAutoGeneratedProductID,{headers: this.httpHeaders}); 
    }
    getAllBrand(type:string){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetAllBrand + type, {headers: this.httpHeaders});
    }
    getExistedBrand(brandId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetExistedBrand + brandId, {headers: this.httpHeaders});
    }
    inActiveBrand(brandId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlinActiveBrand + brandId, {headers: this.httpHeaders});
    }
    createBrand(brand: any){
        return this.http.post<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlCreateBrand, brand);
    }
    updateBrand(brand: any){
        return this.http.post<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlUpdateBrand, brand);
    }
    getAllProduct(type:string){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlgetAllProduct + type, {headers: this.httpHeaders});
    }
    getProductsByCategoryID(categoryId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetProductsByCategoryID + categoryId, {headers: this.httpHeaders});
    }
    getExistedProduct(productId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlgetExistedProduct + productId, {headers: this.httpHeaders});
    }
    addCart(product: AddCart){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlAddCard, product);
    }
    getCartByUserID(userId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetCartByUserID + userId, {headers: this.httpHeaders});
    }
    inActiveCart(cart: CartDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlInActiveCart, cart);
    }
    createOrder(order: CreateOrder){
        return this.http.post<any>(RegisterConstant.libraryApiUrlUser() + this.urlCreateOrder, order);
    }
    getWaitingOrderByUserID(userId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetWaitingOrderByUserID + userId, {headers: this.httpHeaders});
    }
    getProcessingOrderByUserID(userId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetProcessingOrderByUserID + userId, {headers: this.httpHeaders});
    }
    getSuccessOrderByUserID(userId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetSuccessOrderByUserID + userId, {headers: this.httpHeaders});
    }
    getCancelOrderByUserID(userId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetCancelOrderByUserID + userId, {headers: this.httpHeaders});
    }
    deleteAllCartAfterOrder(userId:number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlDeleteAllCartAfterOrder + userId, {headers: this.httpHeaders});
    }
    getProductsByCategoryIDUser(categoryId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetProductsByCategoryID + categoryId, {headers: this.httpHeaders});
    }
    getAllProductByOrderID(orderId :number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlGetAllProductByOrderID + orderId, {headers: this.httpHeaders});
    }
    cancelOrder(orderId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlCancelOrder + orderId, {headers: this.httpHeaders});
    }
    confirmOrder(orderId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlConfirmOrder + orderId, {headers: this.httpHeaders});
    }
    successOrder(orderId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlUser() + this.urlSuccessOrder + orderId, {headers: this.httpHeaders});
    }
    getWaitingOrder(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetWaitingOrder, {headers: this.httpHeaders});
    }
    getProcessingOrder(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetProcessingOrder, {headers: this.httpHeaders});
    }
    getSuccessOrder(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetSuccessOrder, {headers: this.httpHeaders});
    }
    getCancelOrder(){
        return this.http.get<any>(RegisterConstant.libraryApiUrlAdmin() + this.urlGetCancelOrder, {headers: this.httpHeaders});
    }

    //Category Service 
    getAllCategory(type:string){
        return this.http.get<any>(RegisterConstant.libraryApiUrlCategory() + this.urlgetAllCategory + type, {headers: this.httpHeaders});
    }
    inActiveCategory(categoryId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlCategory() + this.urlinActiveCategory + categoryId, {headers: this.httpHeaders});
    }
    getExistedCategory(categoryId: number){
        return this.http.get<any>(RegisterConstant.libraryApiUrlCategory() + this.urlgetExistedCategory + categoryId, {headers: this.httpHeaders});
    }
    createCategory(category: CategoryDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlCategory() + this.urlCreateCategory, category);
    }
    updateCategory(category: ProductDTO){
        return this.http.post<any>(RegisterConstant.libraryApiUrlCategory() + this.urlUpdateCategory, category);
    }
}
